name: Publish Selenium.FramesSearcher.Extensions NuGet Package

on:
  push:
    branches:
      - main # Triggers on pushes to the main branch
    tags:
      - 'framessearcher-v[0-9]+.[0-9]+.[0-9]+*' # Triggers on tags like framessearcher-v1.0.0
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-publish-framessearcher: # Changed job name for clarity
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to check out the repository
      packages: write # Needed to publish to GitHub Packages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Use the .NET version your project targets

    - name: Restore dependencies
      # This project is part of the Selenium.AntiCaptcha.sln
      run: dotnet restore Selenium.AntiCaptcha/Selenium.AntiCaptcha.sln

    - name: Build
      # Build the entire solution, which includes Selenium.FramesSearcher.Extensions
      run: dotnet build Selenium.AntiCaptcha/Selenium.AntiCaptcha.sln --configuration Release --no-restore

    # Optional: Run tests if there are specific tests for FramesSearcher.Extensions
    # - name: Test FramesSearcher.Extensions
    #   run: dotnet test path/to/FramesSearcher.Extensions.Tests.csproj --configuration Release --no-build

    - name: Determine Package Version for FramesSearcher.Extensions
      id: package_version_framessearcher
      shell: bash
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          # Use the tag name, remove 'framessearcher-v' prefix
          VERSION="${{ github.ref_name }}"
          VERSION=${VERSION#framessearcher-v}
          echo "Using tag version for FramesSearcher.Extensions: $VERSION"
        else
          # Path to the Selenium.FramesSearcher.Extensions.csproj
          VERSION_FROM_CSPROJ=$(grep '<Version>' Selenium.AntiCaptcha/Selenium.FramesSearcher.Extensions/Selenium.FramesSearcher.Extensions.csproj | sed -e 's/.*<Version>\(.*\)<\/Version>.*/\1/')
          VERSION="${VERSION_FROM_CSPROJ}-ci-${{ github.run_number }}"
          echo "Using CI version for FramesSearcher.Extensions (main branch): $VERSION"
        fi
        echo "package_version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Pack Selenium.FramesSearcher.Extensions NuGet package
      # Path to the Selenium.FramesSearcher.Extensions.csproj
      run: dotnet pack Selenium.AntiCaptcha/Selenium.FramesSearcher.Extensions/Selenium.FramesSearcher.Extensions.csproj --configuration Release --no-build -p:PackageVersion=${{ steps.package_version_framessearcher.outputs.package_version }} -o ./nuget-packages

    - name: Publish Selenium.FramesSearcher.Extensions to NuGet.org
      if: startsWith(github.ref, 'refs/tags/framessearcher-v') # Only publish to NuGet.org for specific version tags
      run: dotnet nuget push "./nuget-packages/Selenium.FramesSearcher.Extensions*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Publish Selenium.FramesSearcher.Extensions to GitHub Packages
      if: github.ref == 'refs/heads/main' # Only publish to GitHub Packages for pushes to main branch
      run: dotnet nuget push "./nuget-packages/Selenium.FramesSearcher.Extensions*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/RemarkableSolutionsAdmin/index.json" --skip-duplicate